spring.application.name=LinguaLab API
server.port=8085
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/lingualab
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB

lingualab.jwt.secret=lingualab-development-secret-key-change-me-please-32-bytes-minimum
lingualab.jwt.expiration-ms=86400000
lingualab.upload-dir=uploads
lingualab.backend-url=http://localhost:8080
lingualab.public-frontend-url=http://localhost:4200
